application:
  host: 127.0.0.1
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email:
  base_url: "https://api.postmarkapp.com"
  sender_email: # sender email
  auth_token: "secret-token"
