application:
  host: 127.0.0.1
  port: 8000
  base_url: "http://127.0.0.1" # TODO: find a way to set this in the heroku.yaml
  hmac_secret: "longest-secret-ever-that-seem-not-to-be-long-enough-for-actix-web-key"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email:
  base_url: "https://api.postmarkapp.com"
  sender_email: adethormiwa@outlook.com
  auth_token: "secret-token"
  timeout_in_milli: 10000
